name = "picacg"
type = "javascript"
zone_id = ""
account_id = "cca850540843ff76e4b28f506f613d96"

workers_dev = true
compatibility_date = "2022-02-01"

kv_namespaces = [ 
        { binding = "PICACG", id = "9f4d8ecb9e104911813926dd9063dc49" , preview_id = "9f4d8ecb9e104911813926dd9063dc49" }
]

[build]
command = "clear && npm run build"
[build.upload]
format = "service-worker"